# Generated by Django 3.1.14 on 2025-12-23 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=255)),
                ('passport_no', models.CharField(max_length=50, unique=True)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(editable=False)),
                ('date', models.DateField(default=datetime.date.today)),
                ('photo', models.ImageField(upload_to='client_photos/')),
            ],
        ),
    ]
