# Generated by Django 3.1.14 on 2025-12-23 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_image', models.ImageField(upload_to='templates/')),
                ('is_active', models.BooleanField(default=True)),
                ('name_x', models.IntegerField(default=0)),
                ('name_y', models.IntegerField(default=0)),
                ('passport_x', models.IntegerField(default=0)),
                ('passport_y', models.IntegerField(default=0)),
                ('age_x', models.IntegerField(default=0)),
                ('age_y', models.IntegerField(default=0)),
                ('gender_x', models.IntegerField(default=0)),
                ('gender_y', models.IntegerField(default=0)),
                ('date_x', models.IntegerField(default=0)),
                ('date_y', models.IntegerField(default=0)),
                ('photo_x', models.IntegerField(default=0)),
                ('photo_y', models.IntegerField(default=0)),
                ('photo_width', models.IntegerField(default=150)),
                ('photo_height', models.IntegerField(default=180)),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10),
        ),
    ]
