# Generated by Django 3.1.14 on 2025-12-23 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20251223_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='gender_x',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='gender_y',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_height',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_width',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_x',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_y',
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_x1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_x2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_x3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_x4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_y1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_y2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_y3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reporttemplate',
            name='photo_y4',
            field=models.IntegerField(default=0),
        ),
    ]
