# Generated by Django 3.1.14 on 2025-12-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20251223_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='reporttemplate',
            name='font_size',
            field=models.IntegerField(default=14, help_text='Font size for injected text (e.g. 14 for ~8pt)'),
        ),
    ]
