# Generated by Django 3.1.14 on 2025-12-23 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_reporttemplate_font_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_x3',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_x4',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_y3',
        ),
        migrations.RemoveField(
            model_name='reporttemplate',
            name='photo_y4',
        ),
    ]
