# Generated by Django 3.1.14 on 2025-12-23 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_auto_20251223_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporttemplate',
            name='font_size',
            field=models.IntegerField(default=11, help_text='Font size for injected text (e.g. 11 for standard Calibri)'),
        ),
    ]
